#!/usr/bin/env bash

# Get brightness
get_backlight() {
	echo $(brightnessctl -m | cut -d, -f4)
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Brightness: $(get_backlight)"
}

# Increase brightness
inc_backlight() {
	brightnessctl s +1% && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl s 1%- && notify_user
}

case "$1" in
    --get)
        get_backlight
        ;;
    --inc)
        inc_backlight
        ;;
    --dec)
        dec_backlight
        ;;
    *)
        get_backlight
        ;;
esac
